const A={ar:{tagline:'مساعدك الذكي للحياة والسفر',home:'الرئيسية',trip:'رحلتي',discover:'اكتشف',plans:'الباقات',title:'اسأل عن أي شيء.<br>وخلّني أدبّرها معك.',sub:'سفر، عمل، تقنية، دراسة، كتابة، أفكار، منتجات، معلومات عامة أو سؤال من يومك. TRAVO يبحث عند الحاجة ويكمل معك داخل نفس المحادثة.',cityLabel:'المدينة أو الوجهة — اختياري',cityPh:'مثال: الرياض',checking:'جاري فحص الاتصال…',connected:'TRAVO AI متصل • بحث ويب عند الحاجة',offline:'الاتصال متعثر حاليًا — بنحاول مرة ثانية عند الإرسال',hello:'أهلًا 👋 قل لي وش تحتاج — سفر أو أي موضوع ثاني — وأنا أحاول أوصلك لأفضل جواب عملي وأكمل معك من نفس المحادثة.',messagePh:'اكتب اللي في بالك…',send:'إرسال',thinking:'TRAVO يدور لك أفضل جواب…',error:'صار تعثر مؤقت. جرّب نفس الرسالة مرة ثانية وأنا أكمل معك.',trust:'إذا احتاج السؤال معلومة حديثة، TRAVO يحاول يبحث عنها تلقائيًا بدل ما يوقف عند «ما أعرف» — ومع ذلك ما يخترع معلومة غير مؤكدة.',sources:'مصادر استخدمها TRAVO'},en:{tagline:'Your smart assistant for life and travel',home:'Home',trip:'My trip',discover:'Discover',plans:'Plans',title:'Ask about anything.<br>Let’s work it out together.',sub:'Travel, work, technology, study, writing, ideas, products, general information or everyday questions. TRAVO can search when needed and continue in the same conversation.',cityLabel:'City or destination — optional',cityPh:'Example: Riyadh',checking:'Checking connection…',connected:'TRAVO AI connected • web search when needed',offline:'Connection is unstable — we will retry when you send',hello:'Hi 👋 Tell me what you need — travel or anything else — and I’ll work toward the most useful practical answer with you.',messagePh:'Type what’s on your mind…',send:'Send',thinking:'TRAVO is finding the best answer…',error:'There was a temporary issue. Send the same message again and I’ll continue.',trust:'When a question needs current information, TRAVO tries to search instead of stopping at “I don’t know” — without inventing uncertain facts.',sources:'Sources TRAVO used'}};
let lang=localStorage.getItem('travo-lang')||'ar';
let history=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function t(k){return A[lang][k]||k}
function apply(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';localStorage.setItem('travo-lang',lang);$$('[data-a]').forEach(el=>{const v=t(el.dataset.a);if(v)el.innerHTML=v});$$('[data-a-ph]').forEach(el=>el.placeholder=t(el.dataset.aPh));$('#aiLang').textContent=lang==='ar'?'EN':'عربي'}
function bubble(text,type='assistant',sources=[]){const d=document.createElement('div');d.className='chat-bubble '+(type==='user'?'user':type==='error'?'error':'assistant');d.innerHTML=`<b>${type==='user'?(lang==='ar'?'أنت':'You'):'TRAVO AI'}</b><span></span>`;d.querySelector('span').textContent=text;if(type==='assistant'&&Array.isArray(sources)&&sources.length){const wrap=document.createElement('div');wrap.className='ai-sources';const title=document.createElement('small');title.textContent=t('sources');wrap.appendChild(title);sources.slice(0,4).forEach(s=>{if(!s?.url)return;const a=document.createElement('a');a.href=s.url;a.target='_blank';a.rel='noopener';a.textContent=s.title||new URL(s.url).hostname;wrap.appendChild(a)});d.appendChild(wrap)}$('#aiConversation').appendChild(d);d.scrollIntoView({behavior:'smooth',block:'end'});return d}
function saveHistory(){try{localStorage.setItem('travo-ai-history',JSON.stringify(history.slice(-20)))}catch{}}
function loadHistory(){try{const raw=JSON.parse(localStorage.getItem('travo-ai-history')||'[]');if(Array.isArray(raw)){history=raw.filter(x=>x&&['user','assistant'].includes(x.role)&&typeof x.content==='string').slice(-20);history.forEach(x=>bubble(x.content,x.role==='user'?'user':'assistant'))}}catch{history=[]}}
async function check(){const s=$('#aiStatus');try{const r=await fetch('/api/ai',{cache:'no-store'}),j=await r.json();if(!j.ready)throw 0;s.classList.add('ready');s.querySelector('span').textContent=t('connected')}catch{s.classList.remove('ready');s.querySelector('span').textContent=t('offline')}}
async function askServer(msg){const payload={action:'chat',message:msg,language:lang,city:$('#aiCity').value.trim(),history:history.slice(-16)};const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.message||j.error||'AI_ERROR');return j}
async function send(){const input=$('#aiMessage'),msg=input.value.trim();if(!msg)return;bubble(msg,'user');input.value='';$('#aiSubmit').disabled=true;const wait=bubble(t('thinking'));history.push({role:'user',content:msg});saveHistory();try{let j;try{j=await askServer(msg)}catch(first){await new Promise(r=>setTimeout(r,650));j=await askServer(msg)}wait.remove();const answer=j.answer||t('error');bubble(answer,'assistant',j.sources||[]);history.push({role:'assistant',content:answer});saveHistory();check()}catch{wait.remove();bubble(t('error'),'error')}finally{$('#aiSubmit').disabled=false;input.focus()}}
$('#aiLang').onclick=()=>{lang=lang==='ar'?'en':'ar';apply();check()};$('#aiSubmit').onclick=send;$('#aiMessage').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$$('.quick-prompts button').forEach(b=>b.onclick=()=>{$('#aiMessage').value=b.dataset.p;$('#aiMessage').focus()});apply();loadHistory();check();
