const i18n={
 ar:{tagline:'ذكاء السفر، الآن',home:'الرئيسية',discover:'اكتشف',trends:'الترندات الحية',planner:'مخطط الرحلة',near:'بالقرب منك',status:'حالة النظام',daily:'البحث اليومي عن الترندات',saved:'المحفوظات',signin:'تسجيل الدخول',headline:'اعرف أين تذهب<br>قبل الجميع.',sub:'أماكن رائجة، فعاليات اليوم، تجارب جديدة وخطة رحلة ذكية تتغير مع مدينتك ووقتك.',search:'ابحث عن مدينة أو وجهة',explore:'استكشف',trendTitle:'ماذا يحدث الآن؟',trendSub:'بيانات موثقة من تحديث TRAVO اليومي — بدون بطاقات تجريبية.',plannerTitle:'خطط رحلتك بذكاء',destination:'الوجهة',destinationPh:'مثال: دبي',days:'عدد الأيام',planMode:'أسلوب الخطة',modeNear:'الأماكن القريبة',modeTrend:'الأكثر رواجًا',modeDynamic:'ديناميكية حسب موقعي',buildPlan:'أنشئ الخطة',nearTitle:'ماذا يوجد حولك؟',nearSub:'اسمح بالموقع لنرتب الاقتراحات حسب القرب. لا يتم حفظ موقعك في هذه النسخة.',useLocation:'استخدم موقعي',aiSub:'مساعد سفر عملي يفهم المدينة والخطة.',aiUnavailable:'غير متصل',aiMsg:'اسألني عن جدول يوم، اختيار حي، ترتيب التنقل أو خطة سفر كاملة.',aiPh:'مثال: خطط لي ليلة في الرياض',send:'إرسال',statusSub:'نعرض بوضوح ما هو متصل فعليًا وما يزال قيد الربط.',active:'مفعّل',pending:'قيد الربط',auth:'تسجيل الجوال / WhatsApp OTP',pay:'الدفع والاشتراكات',locating:'جارٍ تحديد موقعك…',locationFound:'تم تحديد موقعك. سيستخدم TRAVO الموقع لترتيب خيارات الرحلة عند توفر إحداثيات الأماكن.',locationDenied:'تعذر الوصول للموقع. يمكنك الاستمرار باختيار المدينة يدويًا.',needCity:'اكتب الوجهة أولًا.',day:'اليوم',nearText:'ترتيب يركز على تقليل وقت التنقل وتجميع الأماكن القريبة.',trendText:'ترتيب يركز على التجارب الأعلى رواجًا وتقييمًا.',dynamicText:'ترتيب يتكيف مع موقعك أثناء الرحلة عند السماح بالموقع.',thinking:'TRAVO يفكر…',aiError:'تعذر تشغيل TRAVO AI الآن.',noVerified:'لا توجد عناصر مؤكدة لهذا التصنيف في هذه المدينة الآن. افتح «اكتشف» لرؤية الأقسام الأخرى.',source:'المصدر'},
 en:{tagline:'Travel intelligence, now',home:'Home',discover:'Discover',trends:'Live trends',planner:'Trip planner',near:'Near you',status:'System status',daily:'Daily trend research',saved:'Saved',signin:'Sign in',headline:'Know where to go<br>before everyone else.',sub:'Trending places, today’s events, new experiences and smart itineraries that adapt to your city and time.',search:'Search a city or destination',explore:'Explore',trendTitle:'What’s happening now?',trendSub:'Verified data from TRAVO daily updates — no demo cards.',plannerTitle:'Plan smarter',destination:'Destination',destinationPh:'Example: Dubai',days:'Days',planMode:'Planning style',modeNear:'Nearby-efficient',modeTrend:'Popular & trending',modeDynamic:'Dynamic by my location',buildPlan:'Build plan',nearTitle:'What is around you?',nearSub:'Allow location to rank trip options by proximity. This version does not store your location.',useLocation:'Use my location',aiSub:'A practical travel assistant that understands your city and trip.',aiUnavailable:'Not connected',aiMsg:'Ask for a day plan, neighborhood choice, transport order or a full itinerary.',aiPh:'Example: plan my night in Riyadh',send:'Send',statusSub:'We clearly show what is truly connected and what is still being integrated.',active:'Active',pending:'Pending',auth:'Phone / WhatsApp OTP',pay:'Payments & subscriptions',locating:'Getting your location…',locationFound:'Location received. TRAVO can use it to rank trip choices when venue coordinates are available.',locationDenied:'Location access was unavailable. You can continue by selecting a city manually.',needCity:'Enter a destination first.',day:'Day',nearText:'A structure focused on minimizing travel time and clustering nearby places.',trendText:'A structure focused on popular and highly rated experiences.',dynamicText:'A structure designed to adapt to your live location.',thinking:'TRAVO is thinking…',aiError:'TRAVO AI is unavailable right now.',noVerified:'No verified items for this category in this city right now. Open Discover to explore other sections.',source:'Source'}
};
let lang=localStorage.getItem('travo-lang')||'ar';
let currentCity=localStorage.getItem('travo-city')||'riyadh';
let trendsData={cities:{},updatedAt:null};
let activeFilter='Now';
const t=k=>i18n[lang][k]||k;
const themes={riyadh:{p:'#8b5cf6',image:'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=1800&q=85'},jeddah:{p:'#06b6d4',image:'https://images.unsplash.com/photo-1591604466107-ec97de577aff?auto=format&fit=crop&w=1800&q=85'},alula:{p:'#d97706',image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1800&q=85'},dubai:{p:'#22c1c3',image:'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1800&q=85'},london:{p:'#ef4444',image:'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1800&q=85'},paris:{p:'#60a5fa',image:'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1800&q=85'},tokyo:{p:'#ec4899',image:'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1800&q=85'}};
const statusLabel={Now:{ar:'🔥 Now',en:'🔥 Now'},Tonight:{ar:'🌙 Tonight',en:'🌙 Tonight'},New:{ar:'🆕 New',en:'🆕 New'},Soon:{ar:'🔮 Soon',en:'🔮 Soon'},'Last Chance':{ar:'⏳ Last Chance',en:'⏳ Last Chance'}};
function cityAirport(key){return (window.TRAVO_AIRPORTS||[]).find(a=>a.cityKey===key)}
function cityName(key){const a=cityAirport(key);return lang==='ar'?(a?.cityAr||key):(a?.cityEn||key)}
function populateHomeCities(){const dl=document.getElementById('homeCityOptions');if(!dl)return;dl.innerHTML=(window.TRAVO_AIRPORTS||[]).map(a=>`<option value="${lang==='ar'?a.cityAr:a.cityEn} — ${a.code}">${lang==='ar'?a.countryAr:a.countryEn}</option>`).join('')}
function applyLanguage(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';localStorage.setItem('travo-lang',lang);document.querySelectorAll('[data-t]').forEach(el=>{const v=t(el.dataset.t);if(v)el.innerHTML=v});document.querySelectorAll('[data-ph]').forEach(el=>el.placeholder=t(el.dataset.ph));document.getElementById('langBtn').textContent=lang==='ar'?'EN':'عربي';populateHomeCities();setCity(currentCity,false);renderTrends()}
function setCity(key,scroll=false){currentCity=key||'riyadh';localStorage.setItem('travo-city',currentCity);const a=cityAirport(currentCity),theme=themes[currentCity]||themes.riyadh;document.documentElement.style.setProperty('--p',theme.p);document.querySelector('.hero').style.backgroundImage=`url('${theme.image}')`;document.getElementById('citySearch').value=a?(lang==='ar'?a.cityAr:a.cityEn):currentCity;document.getElementById('heroKicker').textContent=`TRAVO LIVE • ${cityName(currentCity)}`;document.getElementById('planCity').value=cityName(currentCity);renderTrends();if(scroll)document.getElementById('trends').scrollIntoView({behavior:'smooth'})}
function formatUpdated(){if(!trendsData.updatedAt)return '';try{return new Intl.DateTimeFormat(lang==='ar'?'ar-SA':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(trendsData.updatedAt))}catch{return trendsData.updatedAt}}
function renderTrends(){const cards=document.getElementById('trendCards'),empty=document.getElementById('trendEmpty');if(!cards)return;const items=(trendsData.cities?.[currentCity]||[]).filter(x=>x.status===activeFilter).slice(0,6);cards.innerHTML=items.map(item=>{const title=lang==='ar'?item.titleAr:item.titleEn,why=lang==='ar'?item.whyAr:item.whyEn,loc=lang==='ar'?item.locationAr:item.locationEn;return `<article class="card"><div class="cover" style="background-image:url('${item.image||themes[currentCity]?.image||themes.riyadh.image}')"><span class="badge">${statusLabel[item.status]?.[lang]||item.status}</span></div><div class="card-body"><div class="meta"><span>${loc||cityName(currentCity)}</span><span>${item.start||''}</span></div><h3>${title}</h3><p>${why}</p><div class="card-foot"><span class="demo verified-mark">✓ ${item.sourceName||'TRAVO'}</span>${item.sourceUrl?`<a class="ghost card-link" href="${item.sourceUrl}" target="_blank" rel="noopener">${t('source')} ↗</a>`:''}</div></div></article>`}).join('');const has=items.length>0;empty.style.display=has?'none':'block';empty.textContent=t('noVerified');document.getElementById('trendSub').textContent=t('trendSub')+(trendsData.updatedAt?` • ${formatUpdated()}`:'')}

document.getElementById('langBtn').addEventListener('click',()=>{lang=lang==='ar'?'en':'ar';applyLanguage();checkAI()});
document.getElementById('exploreBtn').addEventListener('click',()=>{const a=window.TRAVO_FIND_CITY?window.TRAVO_FIND_CITY(document.getElementById('citySearch').value):null;if(a)setCity(a.cityKey,true);else window.location.href='discover.html'});
document.getElementById('citySearch').addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('exploreBtn').click()});
document.querySelectorAll('.chip').forEach(chip=>chip.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(c=>c.classList.remove('active'));chip.classList.add('active');activeFilter=chip.dataset.filter||'Now';renderTrends()}));

document.getElementById('planBtn').addEventListener('click',()=>{const city=document.getElementById('planCity').value.trim();if(!city){alert(t('needCity'));return}const days=Math.min(30,Math.max(1,Number(document.getElementById('planDays').value)||1));const mode=document.getElementById('planMode').value;const txt=mode==='near'?t('nearText'):mode==='trend'?t('trendText'):t('dynamicText');document.getElementById('itinerary').innerHTML=Array.from({length:days},(_,i)=>`<div class="day"><b>${t('day')} ${i+1} • ${city}</b><span>${txt}</span></div>`).join('')});
document.getElementById('nearBtn').addEventListener('click',()=>{const out=document.getElementById('nearResult');out.textContent=t('locating');if(!navigator.geolocation){out.textContent=t('locationDenied');return}navigator.geolocation.getCurrentPosition(pos=>out.textContent=`${t('locationFound')} (${pos.coords.latitude.toFixed(3)}, ${pos.coords.longitude.toFixed(3)})`,()=>out.textContent=t('locationDenied'),{enableHighAccuracy:false,timeout:8000,maximumAge:300000})});
function addMessage(text,type='assistant'){const el=document.createElement('div');el.className=`bubble ${type==='user'?'user':type==='error'?'error':''}`;el.textContent=text;document.getElementById('aiThread').appendChild(el);el.scrollIntoView({behavior:'smooth',block:'nearest'});return el}
async function checkAI(){const chip=document.getElementById('aiChip'),state=document.getElementById('aiState'),dot=document.getElementById('aiDot');try{const r=await fetch('/api/ai');const j=await r.json();if(!j.ready)throw new Error('not ready');chip.textContent=lang==='ar'?'متصل':'Connected';chip.className='status-pill ready';state.textContent=lang==='ar'?'متصل':'Connected';dot.className='dot good'}catch{chip.textContent=t('aiUnavailable');chip.className='status-pill pending';state.textContent=t('pending');dot.className='dot warn'}}
async function sendAI(){const input=document.getElementById('aiInput'),btn=document.getElementById('aiSend'),message=input.value.trim();if(!message)return;addMessage(message,'user');input.value='';btn.disabled=true;const pending=addMessage(t('thinking'));try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,language:lang,city:cityName(currentCity),tripContext:document.getElementById('itinerary').innerText.slice(0,2400)})});const j=await r.json();pending.remove();if(!r.ok)throw new Error(j.message||j.error);addMessage(j.answer||t('aiError'));checkAI()}catch{pending.remove();addMessage(t('aiError'),'error')}finally{btn.disabled=false;input.focus()}}
document.getElementById('aiSend').addEventListener('click',sendAI);document.getElementById('aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendAI()});
fetch('/data/trends.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(j=>{trendsData=j;document.getElementById('trendDot').className='dot good';document.getElementById('trendState').textContent=lang==='ar'?'متصل':'Connected';document.getElementById('dailyStatus').textContent=(lang==='ar'?'آخر تحديث: ':'Updated: ')+formatUpdated();renderTrends()}).catch(()=>{document.getElementById('trendDot').className='dot warn';document.getElementById('trendState').textContent=t('pending');renderTrends()});
applyLanguage();checkAI();
