const AUTH_COPY={
 ar:{tagline:'ابدأ رحلتك من حساب واحد',home:'الرئيسية',hero:'سجّل مرة.<br>وخلك مع TRAVO طول الرحلة.',heroSub:'بياناتك تحفظ رحلاتك، اختياراتك، خططك اليومية وباقتك في مكان واحد.',emailChecking:'جاري فحص خدمة البريد…',emailReady:'التحقق عبر البريد الإلكتروني جاهز',emailNotReady:'التحقق عبر البريد الإلكتروني يحتاج إكمال الربط',title:'أنشئ حسابك',subtitle:'ندخل بياناتك الأساسية ثم نرسل رمز تحقق OTP إلى بريدك الإلكتروني.',name:'الاسم',email:'البريد الإلكتروني',phone:'رقم الجوال',location:'موقعك / مدينتك',privacy:'نستخدم بريدك للتحقق من الحساب، ونحفظ رقم الجوال ضمن بيانات حسابك. رمز التحقق صالح لمدة 5 دقائق.',readyState:'عبّئ البيانات ثم أرسل رمز التحقق.',sendOtp:'إرسال رمز التحقق إلى البريد',sending:'جاري إرسال الرمز…',invalid:'تأكد من الاسم والبريد ورقم الجوال.',notConfigured:'واجهة التسجيل جاهزة، لكن خدمة إرسال رمز التحقق بالبريد تحتاج إكمال إعداد البريد.',sendFailed:'تعذر إرسال رمز التحقق إلى البريد الآن. حاول مرة أخرى.',rateLimit:'تم طلب رموز كثيرة لهذا البريد. جرّب لاحقًا.',otpTitle:'أدخل رمز التحقق',otpSub:'أرسلنا رمزًا مكوّنًا من 6 أرقام إلى بريدك الإلكتروني.',otp:'رمز التحقق',otpReady:'أدخل الرمز لإكمال إنشاء الحساب.',change:'تعديل البيانات',verify:'تأكيد والدخول إلى TRAVO',resend:'إعادة إرسال الرمز',verifying:'جاري التحقق…',wrongOtp:'الرمز غير صحيح أو انتهت صلاحيته.',success:'تم إنشاء حسابك. جاري فتح TRAVO…',wait:'انتظر دقيقة قبل إعادة إرسال الرمز.'},
 en:{tagline:'One account for your whole trip',home:'Home',hero:'Sign up once.<br>Stay with TRAVO through the journey.',heroSub:'Your account keeps trips, choices, day plans and subscription details together.',emailChecking:'Checking email verification…',emailReady:'Email verification is ready',emailNotReady:'Email verification needs setup',title:'Create your account',subtitle:'Enter your basics, then we send a verification code to your email.',name:'Name',email:'Email',phone:'Mobile number',location:'Your city / location',privacy:'We use your email to verify your account and keep your mobile number in your profile. OTP codes expire after 5 minutes.',readyState:'Fill your details, then send the verification code.',sendOtp:'Send verification code by email',sending:'Sending code…',invalid:'Check your name, email and mobile number.',notConfigured:'Registration is ready, but email OTP delivery still needs setup.',sendFailed:'Could not send the verification code by email. Try again.',rateLimit:'Too many codes were requested for this email. Try again later.',otpTitle:'Enter verification code',otpSub:'We sent a 6-digit code to your email.',otp:'Verification code',otpReady:'Enter the code to finish creating your account.',change:'Edit details',verify:'Verify and enter TRAVO',resend:'Resend code',verifying:'Verifying…',wrongOtp:'The code is invalid or expired.',success:'Your account is ready. Opening TRAVO…',wait:'Please wait one minute before requesting another code.'}
};
let authLang=localStorage.getItem('travo-lang')||'ar',otpEmail='',timerId=null,emailReady=false;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],t=k=>AUTH_COPY[authLang][k]||k;
function apply(){document.documentElement.lang=authLang;document.documentElement.dir=authLang==='ar'?'rtl':'ltr';localStorage.setItem('travo-lang',authLang);$$('[data-auth]').forEach(el=>{const v=t(el.dataset.auth);if(v)el.innerHTML=v});$('#authLang').textContent=authLang==='ar'?'EN':'عربي';refreshBadge()}
function refreshBadge(){const b=$('#emailBadge');if(!b)return;b.classList.toggle('ready',emailReady);b.querySelector('span').textContent=emailReady?t('emailReady'):t('emailNotReady')}
function state(el,msg,type=''){el.textContent=msg;el.className='auth-state'+(type?' '+type:'')}
function nextUrl(){const raw=new URLSearchParams(location.search).get('next')||'trip.html';return /^[a-zA-Z0-9._/-]+(?:\?.*)?$/.test(raw)?raw:'trip.html'}
async function existingSession(){const token=localStorage.getItem('travo-session');if(!token)return false;try{const r=await fetch('/api/profile',{headers:{Authorization:`Bearer ${token}`}});if(!r.ok){localStorage.removeItem('travo-session');return false}location.replace(nextUrl());return true}catch{return false}}
async function checkStatus(){try{const r=await fetch('/api/auth',{cache:'no-store'}),j=await r.json();emailReady=Boolean(j.emailOtpConfigured)}catch{emailReady=false}refreshBadge();$('#sendOtpBtn').disabled=!emailReady}
function profile(){return {name:$('#regName').value.trim(),email:$('#regEmail').value.trim(),phone:$('#regPhone').value.trim(),location:$('#regLocation').value.trim()}}
function valid(p){return p.name.length>=2&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email)&&p.phone.replace(/\D/g,'').length>=9}
function startTimer(seconds=300){clearInterval(timerId);let left=seconds;const el=$('#otpTimer');const paint=()=>{const m=String(Math.floor(left/60)).padStart(2,'0'),s=String(left%60).padStart(2,'0');el.textContent=`${m}:${s}`;left=Math.max(0,left-1)};paint();timerId=setInterval(paint,1000)}
async function requestOtp(){const p=profile(),box=$('#regState');if(!valid(p)){state(box,t('invalid'),'bad');return}if(!emailReady){state(box,t('notConfigured'),'bad');return}$('#sendOtpBtn').disabled=true;state(box,t('sending'));try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'request_otp',profile:p})}),j=await r.json();if(!r.ok){if(j.error==='EMAIL_NOT_CONFIGURED'){emailReady=false;refreshBadge();state(box,t('notConfigured'),'bad')}else if(j.error==='WAIT_BEFORE_RESEND')state(box,t('wait'),'bad');else if(j.error==='OTP_RATE_LIMIT')state(box,t('rateLimit'),'bad');else state(box,t('sendFailed'),'bad');return}otpEmail=p.email.trim().toLowerCase();$('#maskedEmail').textContent=j.emailMasked||'';$('#registrationStep').classList.add('hidden');$('#otpStep').classList.remove('hidden');$('#otpCode').focus();startTimer(j.expiresInSeconds||300)}catch{state(box,t('sendFailed'),'bad')}finally{$('#sendOtpBtn').disabled=!emailReady}}
async function verifyOtp(){const code=$('#otpCode').value.replace(/\D/g,''),box=$('#otpState');if(code.length!==6){state(box,t('wrongOtp'),'bad');return}$('#verifyOtpBtn').disabled=true;state(box,t('verifying'));try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'verify_otp',email:otpEmail,otp:code})}),j=await r.json();if(!r.ok||!j.token){state(box,t('wrongOtp'),'bad');return}localStorage.setItem('travo-session',j.token);localStorage.setItem('travo-user',JSON.stringify(j.user||{}));state(box,t('success'),'good');setTimeout(()=>location.replace(nextUrl()),450)}catch{state(box,t('wrongOtp'),'bad')}finally{$('#verifyOtpBtn').disabled=false}}
$('#authLang').onclick=()=>{authLang=authLang==='ar'?'en':'ar';apply()};$('#sendOtpBtn').onclick=requestOtp;$('#verifyOtpBtn').onclick=verifyOtp;$('#resendOtpBtn').onclick=requestOtp;$('#changeDetailsBtn').onclick=()=>{$('#otpStep').classList.add('hidden');$('#registrationStep').classList.remove('hidden');clearInterval(timerId)};$('#otpCode').addEventListener('input',e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,6)});$('#otpCode').addEventListener('keydown',e=>{if(e.key==='Enter')verifyOtp()});
apply();existingSession().then(done=>{if(!done)checkStatus()});
