const i18n={ar:{overview:'نظرة عامة',customers:'العملاء',plans:'الباقات',activity:'النشاط',demoTitle:'بيانات حية',demoText:'الحسابات المسجلة عبر TRAVO تظهر هنا تلقائيًا.',dashboard:'لوحة التحكم',subtitle:'مراقبة العملاء والاشتراكات والتجارب والباقات.',site:'الموقع',totalUsers:'إجمالي العملاء',premium:'Premium نشط',trials:'تجارب مجانية',trial7:'7 أيام',expiring:'تنتهي قريبًا',next7:'خلال 7 أيام',mrr:'دخل شهري تقديري',sar:'ر.س',customerHint:'العملاء الذين أكملوا التحقق عبر واتساب يظهرون تلقائيًا في هذه القائمة.',search:'ابحث عن عميل',all:'الكل',active:'نشط',trial:'تجربة',expired:'منتهي',client:'العميل',contact:'التواصل',plan:'الباقة',state:'الحالة',trialEnd:'نهاية التجربة',renewal:'التجديد',planHint:'الأسعار مبدئية ويمكن تعديلها قبل الإطلاق.',viewPlans:'معاينة صفحة الباقات',days:'أيام',trialPlan:'وصول Premium كامل خلال فترة التجربة.',month:'ر.س / شهر',monthlyPlan:'الاشتراك الشهري المقترح.',year:'ر.س / سنة',annualPlan:'الاشتراك السنوي المقترح.',loading:'جاري تحميل بيانات العملاء…',empty:'لا يوجد عملاء مسجلون حتى الآن.',loadError:'تعذر تحميل بيانات العملاء الآن.'},en:{overview:'Overview',customers:'Customers',plans:'Plans',activity:'Activity',demoTitle:'Live data',demoText:'Accounts registered through TRAVO appear here automatically.',dashboard:'Dashboard',subtitle:'Monitor customers, subscriptions, trials and plans.',site:'Site',totalUsers:'Total customers',premium:'Active Premium',trials:'Free trials',trial7:'7 days',expiring:'Expiring soon',next7:'Within 7 days',mrr:'Estimated monthly revenue',sar:'SAR',customerHint:'Customers who complete WhatsApp verification appear automatically in this list.',search:'Search customer',all:'All',active:'Active',trial:'Trial',expired:'Expired',client:'Customer',contact:'Contact',plan:'Plan',state:'Status',trialEnd:'Trial ends',renewal:'Renewal',planHint:'Prices are provisional and can be changed before launch.',viewPlans:'Preview plans page',days:'days',trialPlan:'Full Premium access during the trial period.',month:'SAR / month',monthlyPlan:'Proposed monthly subscription.',year:'SAR / year',annualPlan:'Proposed annual subscription.',loading:'Loading customer data…',empty:'No registered customers yet.',loadError:'Could not load customer data.'}};
let customers=[],metrics={total:0,premium:0,trials:0,expiring:0};
let lang=localStorage.getItem('travo-lang')||'ar';
function t(k){return i18n[lang][k]||k}
function fmt(v){if(!v)return'—';try{return new Intl.DateTimeFormat(lang==='ar'?'ar-SA':'en-GB',{dateStyle:'medium'}).format(new Date(v))}catch{return v}}
function statusOf(c){if(c.status==='trial'&&c.trialEnd&&new Date(c.trialEnd).getTime()<Date.now())return'expired';return c.status||'trial'}
function renderRows(){const q=document.getElementById('search').value.trim().toLowerCase();const f=document.getElementById('statusFilter').value;const rows=customers.filter(c=>{const s=statusOf(c);return(f==='all'||s===f)&&(`${c.id||''} ${c.name||''} ${c.phone||''} ${c.email||''} ${c.plan||''} ${c.location||''}`.toLowerCase().includes(q))}).map(c=>{const s=statusOf(c);return`<tr><td><div class="customer"><b>${c.name||'—'}</b><small>${c.id||'—'}${c.location?` • ${c.location}`:''}</small></div></td><td><div class="customer"><b>${c.phone||'—'}</b><small>${c.email||'—'}</small></div></td><td>${c.plan||'—'}</td><td><span class="status ${s}">${t(s)}</span></td><td>${fmt(c.trialEnd)}</td><td>${fmt(c.renewal)}</td></tr>`}).join('');document.getElementById('customerRows').innerHTML=rows||`<tr><td colspan="6">${t('empty')}</td></tr>`}
function renderActivity(){const arr=customers.slice(0,5).map(c=>lang==='ar'?`تم تسجيل ${c.name||c.id} في TRAVO`:`${c.name||c.id} registered with TRAVO`);document.getElementById('activityList').innerHTML=(arr.length?arr:[t('empty')]).map((x,i)=>`<div class="event"><b>${x}</b><span>${i===0?(lang==='ar'?'الأحدث':'Latest'):'—'}</span></div>`).join('')}
function estimateMrr(){return customers.reduce((sum,c)=>{if(statusOf(c)!=='active')return sum;const p=String(c.plan||'').toLowerCase();if(p.includes('annual'))return sum+249/12;if(p.includes('monthly')||p.includes('premium'))return sum+29.99;return sum},0)}
function renderMetrics(){document.getElementById('mUsers').textContent=String(metrics.total||customers.length);document.getElementById('mPremium').textContent=String(metrics.premium||0);document.getElementById('mTrials').textContent=String(metrics.trials||0);document.getElementById('mExpiring').textContent=String(metrics.expiring||0);const mrr=document.getElementById('mMrr');if(mrr)mrr.textContent=estimateMrr().toFixed(0)}
async function loadCustomers(){document.getElementById('customerRows').innerHTML=`<tr><td colspan="6">${t('loading')}</td></tr>`;try{const r=await fetch('/api/admin/customers',{cache:'no-store'}),j=await r.json();if(!r.ok)throw 0;customers=Array.isArray(j.users)?j.users:[];metrics=j.metrics||metrics;renderMetrics();renderRows();renderActivity()}catch{customers=[];renderMetrics();document.getElementById('customerRows').innerHTML=`<tr><td colspan="6">${t('loadError')}</td></tr>`;renderActivity()}}
function apply(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-t]').forEach(el=>{const v=t(el.dataset.t);if(v)el.textContent=v});document.querySelectorAll('[data-ph]').forEach(el=>el.placeholder=t(el.dataset.ph));document.getElementById('langBtn').textContent=lang==='ar'?'EN':'عربي';localStorage.setItem('travo-lang',lang);renderMetrics();renderRows();renderActivity()}
document.getElementById('langBtn').onclick=()=>{lang=lang==='ar'?'en':'ar';apply()};document.getElementById('search').addEventListener('input',renderRows);document.getElementById('statusFilter').addEventListener('change',renderRows);apply();loadCustomers();
