const i18n={ar:{overview:'نظرة عامة',customers:'العملاء',plans:'الباقات',activity:'النشاط',demoTitle:'وضع تجريبي',demoText:'لا توجد بيانات عملاء حقيقية في هذه النسخة.',dashboard:'لوحة التحكم',subtitle:'مراقبة العملاء والاشتراكات والتجارب والباقات.',site:'الموقع',totalUsers:'إجمالي العملاء',premium:'Premium نشط',trials:'تجارب مجانية',trial7:'7 أيام',expiring:'تنتهي قريبًا',next7:'خلال 7 أيام',mrr:'دخل شهري تقديري',sar:'ر.س',customerHint:'البيانات أدناه تجريبية ومخفية جزئيًا حتى يتم ربط قاعدة البيانات.',search:'ابحث عن عميل',all:'الكل',active:'نشط',trial:'تجربة',expired:'منتهي',client:'العميل',contact:'التواصل',plan:'الباقة',state:'الحالة',trialEnd:'نهاية التجربة',renewal:'التجديد',planHint:'الأسعار مبدئية ويمكن تعديلها قبل الإطلاق.',viewPlans:'معاينة صفحة الباقات',days:'أيام',trialPlan:'وصول Premium كامل خلال فترة التجربة.',month:'ر.س / شهر',monthlyPlan:'الاشتراك الشهري المقترح.',year:'ر.س / سنة',annualPlan:'الاشتراك السنوي المقترح.'},en:{overview:'Overview',customers:'Customers',plans:'Plans',activity:'Activity',demoTitle:'Demo mode',demoText:'No real customer data is stored in this version.',dashboard:'Dashboard',subtitle:'Monitor customers, subscriptions, trials and plans.',site:'Site',totalUsers:'Total customers',premium:'Active Premium',trials:'Free trials',trial7:'7 days',expiring:'Expiring soon',next7:'Within 7 days',mrr:'Estimated monthly revenue',sar:'SAR',customerHint:'The data below is demo-only and partially masked until the database is connected.',search:'Search customer',all:'All',active:'Active',trial:'Trial',expired:'Expired',client:'Customer',contact:'Contact',plan:'Plan',state:'Status',trialEnd:'Trial ends',renewal:'Renewal',planHint:'Prices are provisional and can be changed before launch.',viewPlans:'Preview plans page',days:'days',trialPlan:'Full Premium access during the trial period.',month:'SAR / month',monthlyPlan:'Proposed monthly subscription.',year:'SAR / year',annualPlan:'Proposed annual subscription.'}};
const customers=[
{id:'TR-1042',name:'عميل #1042',phone:'••• ••• 1842',plan:'Premium Monthly',status:'active',trial:'—',renewal:'2026-10-02'},
{id:'TR-1047',name:'عميل #1047',phone:'••• ••• 7731',plan:'7-Day Trial',status:'trial',trial:'2026-09-20',renewal:'—'},
{id:'TR-1051',name:'عميل #1051',phone:'••• ••• 2206',plan:'Premium Annual',status:'active',trial:'—',renewal:'2027-09-11'},
{id:'TR-1054',name:'عميل #1054',phone:'••• ••• 5190',plan:'7-Day Trial',status:'trial',trial:'2026-09-18',renewal:'—'},
{id:'TR-1033',name:'عميل #1033',phone:'••• ••• 0917',plan:'Premium Monthly',status:'expired',trial:'—',renewal:'2026-09-12'}
];
const activity={ar:['بدأ عميل #1054 تجربة Premium','تم تجديد اشتراك عميل #1042','تم تحديث أسعار الباقات التجريبية','تم تشغيل تحديثات TRAVO اليومية'],en:['Customer #1054 started a Premium trial','Customer #1042 renewed a subscription','Draft plan pricing was updated','TRAVO daily updates are active']};
let lang=localStorage.getItem('travo-lang')||'ar';
function t(k){return i18n[lang][k]||k}
function renderRows(){const q=document.getElementById('search').value.trim().toLowerCase();const f=document.getElementById('statusFilter').value;const rows=customers.filter(c=>(f==='all'||c.status===f)&&(`${c.id} ${c.name} ${c.phone} ${c.plan}`.toLowerCase().includes(q))).map(c=>`<tr><td><div class="customer"><b>${c.name}</b><small>${c.id}</small></div></td><td>${c.phone}</td><td>${c.plan}</td><td><span class="status ${c.status}">${t(c.status)}</span></td><td>${c.trial}</td><td>${c.renewal}</td></tr>`).join('');document.getElementById('customerRows').innerHTML=rows||`<tr><td colspan="6">—</td></tr>`}
function renderActivity(){document.getElementById('activityList').innerHTML=activity[lang].map((x,i)=>`<div class="event"><b>${x}</b><span>${i===0?'Today':'—'}</span></div>`).join('')}
function apply(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-t]').forEach(el=>{const v=t(el.dataset.t);if(v)el.textContent=v});document.querySelectorAll('[data-ph]').forEach(el=>el.placeholder=t(el.dataset.ph));document.getElementById('langBtn').textContent=lang==='ar'?'EN':'عربي';localStorage.setItem('travo-lang',lang);renderRows();renderActivity()}
document.getElementById('langBtn').onclick=()=>{lang=lang==='ar'?'en':'ar';apply()};
document.getElementById('search').addEventListener('input',renderRows);document.getElementById('statusFilter').addEventListener('change',renderRows);
apply();
