let lang=localStorage.getItem('travo-lang')||'ar';
let trends={cities:{},updatedAt:null},guides={cities:{},updatedAt:null},sources={cities:{}};
let city=localStorage.getItem('travo-city')||'riyadh',view='events';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const themes={riyadh:'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=1800&q=85',jeddah:'https://images.unsplash.com/photo-1591604466107-ec97de577aff?auto=format&fit=crop&w=1800&q=85',alula:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1800&q=85',dubai:'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1800&q=85',london:'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1800&q=85',paris:'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1800&q=85',tokyo:'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1800&q=85'};
const labels={events:{ar:['EVENTS','الفعاليات','فعاليات حالية وقادمة مع التاريخ والسعر والمصدر.'],en:['EVENTS','Events','Current and upcoming events with date, price and source.']},conferences:{ar:['CONFERENCES','المؤتمرات والمعارض','مؤتمرات ومعارض أعمال ومهنية من المصادر الرسمية للمدينة.'],en:['CONFERENCES','Conferences & exhibitions','Business conferences and exhibitions from official city sources.']},activities:{ar:['ACTIVITIES','الأنشطة','أنشطة وأشياء تقدر تسويها أثناء وجودك في المدينة.'],en:['ACTIVITIES','Activities','Things to do while you are in the city.']},entertainment:{ar:['ENTERTAINMENT','الترفيه','عروض، كوميديا وترفيه حي.'],en:['ENTERTAINMENT','Entertainment','Shows, comedy and live entertainment.']},concerts:{ar:['CONCERTS','الحفلات','حفلات موسيقية وعروض مباشرة.'],en:['CONCERTS','Concerts','Music concerts and live performances.']},experiences:{ar:['EXPERIENCES','التجارب','تجارب موسمية وثقافية ومميزة.'],en:['EXPERIENCES','Experiences','Seasonal, cultural and distinctive experiences.']},awardRestaurants:{ar:['AWARDS 2026','مطاعم فائزة هذا العام','نعرض فقط الجوائز الموثقة لسنة 2026، بدون تحويل التقييم إلى جائزة.'],en:['AWARDS 2026','Award-winning restaurants','Only verified 2026 awards are shown; ratings are not treated as awards.']},awardCoffee:{ar:['AWARDS 2026','مقاهي فائزة هذا العام','نعرض فقط الجوائز الموثقة لسنة 2026.'],en:['AWARDS 2026','Award-winning coffee shops','Only verified 2026 awards are shown.']}};
const status={Now:{ar:'🔥 الآن',en:'🔥 Now'},Tonight:{ar:'🌙 الليلة',en:'🌙 Tonight'},New:{ar:'🆕 جديد',en:'🆕 New'},Soon:{ar:'🔮 قريبًا',en:'🔮 Soon'},'Last Chance':{ar:'⏳ آخر فرصة',en:'⏳ Last chance'}};
function airport(k){return (window.TRAVO_AIRPORTS||[]).find(x=>x.cityKey===k)}function cityName(k){const a=airport(k);return lang==='ar'?(a?.cityAr||k):(a?.cityEn||k)}
function fillCities(){const dl=$('#discoverCities');dl.innerHTML=(window.TRAVO_AIRPORTS||[]).map(a=>`<option value="${lang==='ar'?a.cityAr:a.cityEn} — ${a.code}">${lang==='ar'?a.countryAr:a.countryEn}</option>`).join('')}
function dateUpdated(){const d=trends.updatedAt||guides.updatedAt;if(!d)return lang==='ar'?'بانتظار التحديث':'Awaiting update';try{return new Intl.DateTimeFormat(lang==='ar'?'ar-SA':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d))}catch{return d}}
function mapUrl(text){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(text)}`}
function kindOf(x){const raw=`${x.kind||''} ${x.category||''} ${x.titleAr||''} ${x.titleEn||''}`.toLowerCase();if(/conference|convention|expo|exhibition|معرض|مؤتمر|gisec|fashion week/.test(raw))return'conference';if(/concert|music|live|حفلة|حفل|موسيقى|غناء/.test(raw))return'concert';if(/comedy|stand.?up|entertainment|ترفيه|كوميديا|عرض/.test(raw))return'entertainment';if(/experience|activity|sports|adventure|شاطئ|تجربة|نشاط|رياض/.test(raw))return'experience';return'event'}
function match(x){const k=kindOf(x);if(view==='events')return true;if(view==='conferences')return k==='conference';if(view==='activities')return ['experience','event'].includes(k)&&!['conference','concert','entertainment'].includes(k);if(view==='entertainment')return k==='entertainment';if(view==='concerts')return k==='concert';if(view==='experiences')return k==='experience';return false}
function eventCard(x){const title=lang==='ar'?x.titleAr:x.titleEn,why=lang==='ar'?x.whyAr:x.whyEn,loc=lang==='ar'?x.locationAr:x.locationEn;const when=x.start?`${x.start}${x.end&&x.end!==x.start?' → '+x.end:''}`:'—';return `<article class="live-card"><div class="live-cover" style="background-image:url('${x.image||themes[city]||themes.riyadh}')"><span class="live-status">${status[x.status]?.[lang]||x.status||''}</span></div><div class="live-body"><div class="live-meta"><span>${kindOf(x).toUpperCase()}</span><span>${when}</span></div><h3>${title||''}</h3><p>${why||''}</p><div class="fact-row"><span>◷ ${when}</span><span>◈ ${x.price||'—'}</span></div><div class="card-actions">${loc?`<a class="ghost mini-action" target="_blank" rel="noopener" href="${mapUrl(loc+' '+cityName(city))}">📍 ${lang==='ar'?'الموقع':'Map'}</a>`:''}${x.sourceUrl?`<a class="primary mini-action" target="_blank" rel="noopener" href="${x.sourceUrl}">${lang==='ar'?'المصدر / الحجز':'Source / tickets'} ↗</a>`:''}</div><small class="source-note">${x.sourceName||'TRAVO'}</small></div></article>`}
function awardCard(v,type){const sum=lang==='ar'?v.reviewSummaryAr:v.reviewSummaryEn;return `<article class="venue-card award-card"><div class="venue-card-head"><div><span class="venue-area">${v.awardYear||2026} • ${v.area||cityName(city)}</span><h3>${v.name}</h3></div>${v.rating?`<span class="rating">★ ${Number(v.rating).toFixed(1)}</span>`:''}</div><div class="award-label">🏆 ${v.awardName||v.award|| (lang==='ar'?'جائزة موثقة':'Verified award')}</div><p>${sum||v.awardSummaryAr||v.awardSummaryEn||''}</p><div class="card-actions"><a class="ghost mini-action" target="_blank" rel="noopener" href="${mapUrl(v.name+' '+cityName(city))}">📍 ${lang==='ar'?'الموقع':'Map'}</a>${v.sourceUrl?`<a class="primary mini-action" target="_blank" rel="noopener" href="${v.sourceUrl}">${lang==='ar'?'مصدر الجائزة':'Award source'} ↗</a>`:''}</div></article>`}
function renderSources(){const arr=sources.cities?.[city]||[];$('#officialSources').innerHTML=arr.length?arr.map(s=>`<a href="${s.url}" target="_blank" rel="noopener"><b>${s.name}</b><small>${s.type}</small></a>`).join(''):`<span class="muted">${lang==='ar'?'سيتم إضافة المصدر الرسمي بعد التحقق.':'Official source will be added after verification.'}</span>`;$('#sourceCityName').textContent=cityName(city)}
function render(){const cfg=labels[view][lang];$('#viewKicker').textContent=cfg[0];$('#viewTitle').textContent=cfg[1];$('#viewDescription').textContent=cfg[2];$('#cityTitle').textContent=cityName(city);$('#categoryQuestion').textContent=lang==='ar'?`وش ودك تشوف في ${cityName(city)}؟`:`What do you want to explore in ${cityName(city)}?`;$('#updatedLabel').textContent=(lang==='ar'?'آخر تحديث: ':'Updated: ')+dateUpdated();let html='';if(view==='awardRestaurants'||view==='awardCoffee'){const g=guides.cities?.[city]||{};const arr=view==='awardRestaurants'?(g.awardRestaurants||g.awards?.restaurants||[]):(g.awardCoffee||g.awards?.coffee||[]);html=arr.filter(v=>Number(v.awardYear||2026)===2026).map(v=>awardCard(v,view)).join('')}else html=(trends.cities?.[city]||[]).filter(match).map(eventCard).join('');$('#discoverResults').innerHTML=html;$('#emptyState').classList.toggle('hidden',Boolean(html));$('#emptyTitle').textContent=(view==='awardRestaurants'||view==='awardCoffee')?(lang==='ar'?'لا توجد جائزة 2026 موثقة في بيانات TRAVO لهذه المدينة حتى الآن.':'No verified 2026 award data is available for this city yet.'):(lang==='ar'?'لا توجد بيانات مؤكدة لهذا القسم الآن.':'No verified items in this section right now.');$('#emptyText').textContent=lang==='ar'?'TRAVO لن يحوّل التقييم أو الشهرة إلى معلومة أو جائزة غير موثقة.':'TRAVO will not turn ratings or popularity into an unverified fact or award.';renderSources()}
function setCity(k){city=k||'riyadh';localStorage.setItem('travo-city',city);const a=airport(city);$('#discoverCity').value=a?(lang==='ar'?a.cityAr:a.cityEn):city;document.documentElement.style.setProperty('--discover-image',`url('${themes[city]||themes.riyadh}')`);render()}
function setLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';localStorage.setItem('travo-lang',lang);$('#discoverLang').textContent=lang==='ar'?'EN':'عربي';fillCities();render()}
$('#discoverLang').onclick=()=>{lang=lang==='ar'?'en':'ar';setLang()};$('#changeCityBtn').onclick=()=>{const a=window.TRAVO_FIND_CITY?.($('#discoverCity').value);if(a)setCity(a.cityKey)};$('#discoverCity').addEventListener('keydown',e=>{if(e.key==='Enter')$('#changeCityBtn').click()});$$('#categoryGrid button').forEach(b=>b.onclick=()=>{view=b.dataset.view;$$('#categoryGrid button').forEach(x=>x.classList.toggle('active',x===b));$('#discoverResults').scrollIntoView({behavior:'smooth',block:'start'});render()});
Promise.all([fetch('/data/trends.json',{cache:'no-store'}).then(r=>r.json()),fetch('/data/city-guides.json',{cache:'no-store'}).then(r=>r.json()),fetch('/data/event-sources.json',{cache:'no-store'}).then(r=>r.json())]).then(([t,g,s])=>{trends=t;guides=g;sources=s;$('#dataFreshness').textContent=(lang==='ar'?'تحديثات شبه يومية • ':'Twice-daily updates • ')+dateUpdated();setCity(city)}).catch(()=>{setCity(city)});setLang();
