let discoverLang=localStorage.getItem('travo-lang')||'ar';
let trendsData={cities:{},updatedAt:null};
let guidesData={cities:{},updatedAt:null};
let currentCity=localStorage.getItem('travo-city')||'riyadh';
let currentView='now';
const DQ=s=>document.querySelector(s),DQA=s=>[...document.querySelectorAll(s)];
const cityThemes={riyadh:'https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=1800&q=85',jeddah:'https://images.unsplash.com/photo-1591604466107-ec97de577aff?auto=format&fit=crop&w=1800&q=85',alula:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1800&q=85',dubai:'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1800&q=85',london:'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1800&q=85',paris:'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1800&q=85',tokyo:'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1800&q=85'};
const statusLabel={Now:{ar:'🔥 يحدث الآن',en:'🔥 Happening now'},New:{ar:'🆕 جديد',en:'🆕 New'},Soon:{ar:'🔮 قريبًا',en:'🔮 Soon'},Tonight:{ar:'🌙 الليلة',en:'🌙 Tonight'},'Last Chance':{ar:'⏳ آخر فرصة',en:'⏳ Last chance'}};
const views={
 now:{ar:['HAPPENING NOW','ماذا يحدث الآن؟','الأشياء المؤكدة التي تحدث الآن أو افتتحت للتو.'],en:['HAPPENING NOW','What is happening now?','Verified things happening now or newly opened.']},
 events:{ar:['EVENTS','الفعاليات','حفلات، معارض، مهرجانات ورياضة من مصادر موثقة.'],en:['EVENTS','Events','Concerts, exhibitions, festivals and sports from verified sources.']},
 restaurants:{ar:['FOOD','المطاعم','خيارات طعام محدثة مع التقييم وحجم المراجعات وانطباع مختصر.'],en:['FOOD','Restaurants','Updated dining options with ratings, review volume and a short review takeaway.']},
 coffee:{ar:['SPECIALTY COFFEE','القهوة المختصة','مقاهي مختارة بناءً على بيانات التقييمات ومراجعات القهوة.'],en:['SPECIALTY COFFEE','Specialty coffee','Coffee spots selected from rating and review data.']},
 experiences:{ar:['EXPERIENCES','التجارب','تجارب ثقافية وترفيهية وأشياء جديدة تستحق وقتك.'],en:['EXPERIENCES','Experiences','Culture, entertainment and new experiences worth your time.']},
 upcoming:{ar:['UPCOMING','القادم','أشياء قادمة تستحق أن تضيفها قبل الرحلة.'],en:['UPCOMING','Upcoming','Things worth adding before your trip.']}
};
function airportForCity(key){return (window.TRAVO_AIRPORTS||[]).find(a=>a.cityKey===key)}
function cityName(key){const a=airportForCity(key);return discoverLang==='ar'?(a?.cityAr||key):(a?.cityEn||key)}
function initCities(){const dl=DQ('#discoverCities');if(!dl)return;dl.innerHTML=(window.TRAVO_AIRPORTS||[]).map(a=>`<option value="${discoverLang==='ar'?a.cityAr:a.cityEn} — ${a.code}">${discoverLang==='ar'?a.airportAr:a.airportEn}</option>`).join('')}
function setLanguage(){document.documentElement.lang=discoverLang;document.documentElement.dir=discoverLang==='ar'?'rtl':'ltr';localStorage.setItem('travo-lang',discoverLang);DQ('#discoverLang').textContent=discoverLang==='ar'?'EN':'عربي';initCities();render()}
function setCity(key){currentCity=key||'riyadh';localStorage.setItem('travo-city',currentCity);const a=airportForCity(currentCity);DQ('#cityTitle').textContent=cityName(currentCity);DQ('#discoverCity').value=a?(discoverLang==='ar'?a.cityAr:a.cityEn):currentCity;document.documentElement.style.setProperty('--discover-image',`url('${cityThemes[currentCity]||cityThemes.riyadh}')`);render()}
function formatUpdated(){if(!trendsData.updatedAt)return discoverLang==='ar'?'بانتظار أول تحديث':'Awaiting first update';try{return new Intl.DateTimeFormat(discoverLang==='ar'?'ar-SA':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(trendsData.updatedAt))}catch{return trendsData.updatedAt}}
function eventCard(item){const title=discoverLang==='ar'?item.titleAr:item.titleEn;const why=discoverLang==='ar'?item.whyAr:item.whyEn;const loc=discoverLang==='ar'?item.locationAr:item.locationEn;const stat=statusLabel[item.status]?.[discoverLang]||item.status;return `<article class="live-card" data-event-id="${item.id}"><div class="live-cover" style="background-image:url('${item.image||cityThemes[currentCity]||cityThemes.riyadh}')"><span class="live-status">${stat}</span></div><div class="live-body"><div class="live-meta"><span>${item.category}</span><span>${item.start||''}</span></div><h3>${title}</h3><p>${why}</p><div class="live-meta"><span>${loc||''}</span><span>${item.price||''}</span></div></div></article>`}
function venueCard(v,meal){const summary=discoverLang==='ar'?v.reviewSummaryAr:v.reviewSummaryEn;const mealLabel={breakfast:{ar:'فطور',en:'Breakfast'},lunch:{ar:'غداء',en:'Lunch'},dinner:{ar:'عشاء',en:'Dinner'},coffee:{ar:'قهوة',en:'Coffee'}}[meal]?.[discoverLang]||meal;return `<article class="venue-card"><div class="venue-card-head"><div><span class="venue-area">${mealLabel} • ${v.area||''}</span><h3>${v.name}</h3></div><span class="rating">★ ${Number(v.rating||0).toFixed(1)}</span></div><p>${summary||''}</p><div class="live-meta"><span>${v.reviews?`${v.reviews.toLocaleString()} ${discoverLang==='ar'?'مراجعة':'reviews'}`:''}</span>${v.sourceUrl?`<a class="source-link" target="_blank" rel="noopener" href="${v.sourceUrl}">${v.sourceLabel||'Source'} ↗</a>`:`<span>${v.sourceLabel||''}</span>`}</div></article>`}
function uniqueVenues(list){const seen=new Set();return list.filter(x=>{const k=x.v.name.toLowerCase();if(seen.has(k))return false;seen.add(k);return true})}
function render(){const cfg=views[currentView][discoverLang];DQ('#viewKicker').textContent=cfg[0];DQ('#viewTitle').textContent=cfg[1];DQ('#viewDescription').textContent=cfg[2];DQ('#cityTitle').textContent=cityName(currentCity);DQ('#updatedLabel').textContent=(discoverLang==='ar'?'آخر تحديث: ':'Updated: ')+formatUpdated();const out=DQ('#discoverResults'),empty=DQ('#emptyState');let html='';const events=trendsData.cities?.[currentCity]||[];const guide=guidesData.cities?.[currentCity];if(currentView==='now')html=events.filter(e=>['Now','New','Tonight','Last Chance'].includes(e.status)).map(eventCard).join('');if(currentView==='events')html=events.filter(e=>['Event','Sports','Culture'].includes(e.category)).map(eventCard).join('');if(currentView==='experiences')html=events.filter(e=>['Experience','Culture','New','Sports'].includes(e.category)).map(eventCard).join('');if(currentView==='upcoming')html=events.filter(e=>e.status==='Soon').map(eventCard).join('');if(currentView==='restaurants'&&guide){const all=uniqueVenues(['breakfast','lunch','dinner'].flatMap(meal=>(guide[meal]||[]).map(v=>({v,meal}))));html=all.map(x=>venueCard(x.v,x.meal)).join('')}if(currentView==='coffee'&&guide)html=(guide.coffee||[]).map(v=>venueCard(v,'coffee')).join('');out.innerHTML=html;empty.classList.toggle('hidden',Boolean(html));DQA('.live-card').forEach(c=>c.onclick=()=>openEvent(c.dataset.eventId))}
function openEvent(id){const item=(trendsData.cities?.[currentCity]||[]).find(x=>x.id===id);if(!item)return;const title=discoverLang==='ar'?item.titleAr:item.titleEn,why=discoverLang==='ar'?item.whyAr:item.whyEn,loc=discoverLang==='ar'?item.locationAr:item.locationEn;DQ('#discoverDialogBody').innerHTML=`<div class="dialog-inner"><p class="eyebrow">${statusLabel[item.status]?.[discoverLang]||item.status} • ${item.category}</p><h2>${title}</h2><p>${why}</p><div class="status-list"><div class="status-row"><span>${discoverLang==='ar'?'الموعد':'When'}</span><b>${item.start||'—'}${item.end&&item.end!==item.start?' → '+item.end:''}</b></div><div class="status-row"><span>${discoverLang==='ar'?'المكان':'Where'}</span><b>${loc||'—'}</b></div><div class="status-row"><span>${discoverLang==='ar'?'السعر':'Price'}</span><b>${item.price||'—'}</b></div></div><div class="dialog-actions"><button class="ghost" onclick="document.getElementById('discoverDialog').close()">${discoverLang==='ar'?'إغلاق':'Close'}</button>${item.sourceUrl?`<a class="primary link-btn" target="_blank" rel="noopener" href="${item.sourceUrl}">${discoverLang==='ar'?'المصدر الرسمي':'Official source'} ↗</a>`:''}</div></div>`;DQ('#discoverDialog').showModal()}
DQ('#discoverLang').onclick=()=>{discoverLang=discoverLang==='ar'?'en':'ar';setLanguage()};
DQA('#discoverTabs button').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;DQA('#discoverTabs button').forEach(x=>x.classList.toggle('active',x===b));render()});
DQ('#changeCityBtn').onclick=()=>{const value=DQ('#discoverCity').value;const a=window.TRAVO_FIND_CITY?window.TRAVO_FIND_CITY(value):null;if(a)setCity(a.cityKey)};
DQ('#discoverCity').addEventListener('keydown',e=>{if(e.key==='Enter')DQ('#changeCityBtn').click()});
Promise.all([fetch('/data/trends.json',{cache:'no-store'}).then(r=>r.json()),fetch('/data/city-guides.json',{cache:'no-store'}).then(r=>r.json())]).then(([t,g])=>{trendsData=t;guidesData=g;DQ('#dataFreshness').textContent=(discoverLang==='ar'?'بيانات محدثة: ':'Data updated: ')+formatUpdated();setCity(currentCity)}).catch(()=>{trendsData={cities:{}};guidesData={cities:{}};setCity(currentCity)});
setLanguage();
