(function(){
  function normArea(v){return String(v||'').toLowerCase().replace(/[–—-]/g,' ').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim()}
  function areaAffinity(venueArea,dayArea){const a=normArea(venueArea),b=normArea(dayArea);if(!a||!b)return 0;if(a===b||a.includes(b)||b.includes(a))return 100;const aw=new Set(a.split(' ').filter(x=>x.length>2)),bw=b.split(' ').filter(x=>x.length>2);const common=bw.filter(x=>aw.has(x)).length;return common*28}
  function smartScore(v,style,dayArea){const rating=Number(v.rating||0),reviews=Number(v.reviews||0);let score=rating*18+Math.log10(reviews+1)*6+areaAffinity(v.area,dayArea);if((style==='nearby'||style==='dynamic')&&typeof distanceKm==='function'){const d=distanceKm(v,userCoords);if(d!==null)score+=Math.max(-40,130-d*12)}return score}

  pickVenueOptions=function(list,dayIndex,style,dayArea){if(!Array.isArray(list)||!list.length)return[];const ranked=[...list].sort((a,b)=>smartScore(b,style,dayArea)-smartScore(a,style,dayArea));if(ranked.length<=3)return ranked;const bestArea=ranked.filter(v=>areaAffinity(v.area,dayArea)>0);if(bestArea.length>=3)return bestArea.slice(0,3);const lead=bestArea.slice(0,2);for(const v of ranked){if(lead.length>=3)break;if(!lead.includes(v))lead.push(v)}return lead.slice(0,3)};

  mealBlock=function(titleKey,meal,dayIndex,p,day){const city=guideData.cities?.[p.destinationKey];const list=city?.[meal]||[];const opts=pickVenueOptions(list,dayIndex,p.planStyle,day?.area||'');if(!opts.length)return `<section class="meal-block unavailable"><div class="meal-title"><b>${tr(titleKey)}</b></div><p>${tr('verifiedUnavailable')}</p></section>`;return `<section class="meal-block"><div class="meal-title"><div><b>${tr(titleKey)}</b>${day?.area?`<small class="cluster-hint">${lang==='ar'?'حول منطقة اليوم':'Near today’s area'} • ${day.area}</small>`:''}</div><span>${p.planStyle==='nearby'?'📍':p.planStyle==='dynamic'?'✦':'🔥'}</span></div><div class="venue-options">${opts.map(v=>venueOption(v,dayIndex+1,meal)).join('')}</div></section>`};

  function timeLabel(kind,p,index,total){const packed=p.pace==='packed',relaxed=p.pace==='relaxed';const defaults={breakfast:relaxed?'09:30':'08:30',morning:relaxed?'11:00':'10:00',lunch:packed?'13:00':'13:30',afternoon:packed?'14:30':'15:30',coffee:'17:00',dinner:relaxed?'20:30':'20:00',evening:packed?'22:00':'21:30'};if(index===0&&p.arrivalTime&&['breakfast','morning'].includes(kind))return '';if(index===total-1&&p.returnTime&&['dinner','evening'].includes(kind))return '';return defaults[kind]||''}
  function slot(icon,label,time,text){if(!text)return'';return `<div class="activity-slot timeline-slot"><div class="timeline-time">${time||'•'}</div><div><b>${icon} ${label}</b><span>${text}</span></div></div>`}

  renderItinerary=function(data,p,save=true){const days=data.days||[];$('#tripSummary').textContent=data.summary||tr('itinerarySub');$('#tripOverview').innerHTML=[p.destination,p.hotel||null,p.tripType,p.pace,p.budget,planModeText(p.planStyle)].filter(Boolean).map(x=>`<span class="overview-pill">${x}</span>`).join('');$('#fullItinerary').innerHTML=days.map((d,i)=>`<article class="trip-day"><div class="trip-day-head"><div><b>${tr('day')} ${d.day||i+1}${d.title?' • '+d.title:''}</b><small>${d.date||''}</small></div>${d.area?`<span class="day-cluster">◎ ${d.area}</span>`:''}</div>${d.routeNote?`<div class="route-note"><b>${lang==='ar'?'منطق اليوم':'Today’s route'}</b><span>${d.routeNote}</span></div>`:''}<div class="timeline-row"><span>${timeLabel('breakfast',p,i,days.length)}</span><b>${tr('breakfast')}</b></div>${mealBlock('breakfast','breakfast',i,p,d)}${slot('☀',tr('morning'),timeLabel('morning',p,i,days.length),d.morning)}<div class="timeline-row"><span>${timeLabel('lunch',p,i,days.length)}</span><b>${tr('lunch')}</b></div>${mealBlock('lunch','lunch',i,p,d)}${slot('◐',tr('afternoon'),timeLabel('afternoon',p,i,days.length),d.afternoon)}<div class="timeline-row"><span>${timeLabel('coffee',p,i,days.length)}</span><b>${tr('coffee')}</b></div>${mealBlock('coffee','coffee',i,p,d)}<div class="timeline-row"><span>${timeLabel('dinner',p,i,days.length)}</span><b>${tr('dinner')}</b></div>${mealBlock('dinner','dinner',i,p,d)}${slot('☾',tr('evening'),timeLabel('evening',p,i,days.length),d.evening)}${d.note?`<div class="inline-note">${d.note}</div>`:''}</article>`).join('');if(save)localStorage.setItem('travo-trip-draft',JSON.stringify({payload:p,itinerary:data,selectedVenues}));showStep(4);applyDestinationTheme((p.destinationKey||p.destination||'').toLowerCase())};
})();
