const entryStyle=document.createElement('link');entryStyle.rel='stylesheet';entryStyle.href='trip-entry.css';document.head.appendChild(entryStyle);
const smartStyle=document.createElement('link');smartStyle.rel='stylesheet';smartStyle.href='trip-smart.css';document.head.appendChild(smartStyle);
const ENTRY={ar:{startStep:'البداية',hero:'خطط رحلتك بذكاء.<br>وخلّ TRAVO يرتب التفاصيل.',heroSub:'ابدأ باختيار أسلوب التخطيط، وبعدها عبّئ بيانات الرحلة أو ارفع تذاكر الطيران ليقرأها TRAVO تلقائيًا.',startTitle:'خطط رحلتك بذكاء',startSub:'حدد أولًا كيف تبغى TRAVO يرتب يومك، ثم اختر طريقة إدخال الرحلة.',manualTitle:'تعبئة بيانات الرحلة',manualSub:'المغادرة والعودة ووقتهما، والفندق اختياري.',ticketMethodTitle:'رفع تذاكر الطيران',ticketMethodSub:'صوّر أو ارفع التذكرة وTRAVO يقرأ بياناتها تلقائيًا.',goalsSub:'الآن نكمل اهتماماتك، وTRAVO يستخدم أسلوب التخطيط اللي اخترته من البداية.'},en:{startStep:'Start',hero:'Plan your trip smarter.<br>Let TRAVO handle the details.',heroSub:'Choose your planning style first, then enter your trip manually or upload flight tickets for TRAVO to read.',startTitle:'Plan your trip smarter',startSub:'First choose how TRAVO should organize your days, then choose how to enter your trip.',manualTitle:'Enter trip details',manualSub:'Departure and return dates/times. Hotel is optional.',ticketMethodTitle:'Upload flight tickets',ticketMethodSub:'Take a photo or upload your ticket and TRAVO reads the trip details automatically.',goalsSub:'Now add your interests. TRAVO keeps the planning style you selected at the start.'}};
function entryLang(){return localStorage.getItem('travo-lang')||'ar'}
function applyEntryCopy(){const l=entryLang();document.querySelectorAll('[data-entry-i]').forEach(el=>{const v=ENTRY[l]?.[el.dataset.entryI];if(v)el.innerHTML=v})}
function resolveDestinationKey(raw){const a=window.TRAVO_FIND_CITY?.(raw||'');if(a)return a.cityKey;const q=String(raw||'').trim().toLowerCase();return Object.keys(window.TRAVO_DESTINATION_THEMES||{}).find(k=>q.includes(k))||null}
function setSaudiStartVisual(){window.TRAVO_RESET_BRAND_THEME?.();const img=window.TRAVO_SAUDI_GALLERY?.[3]?.image||window.TRAVO_DEFAULT_SAUDI_IMAGE;if(img)document.documentElement.style.setProperty('--trip-hero',`url('${img}')`)}
applyDestinationTheme=function(raw){const k=resolveDestinationKey(raw);if(!k){setSaudiStartVisual();return}window.TRAVO_APPLY_DESTINATION_THEME?.(k,{target:'trip'});localStorage.setItem('travo-trip-theme',k)};
function watchDestination(){const el=document.getElementById('destination');if(!el)return;let timer;const run=()=>{clearTimeout(timer);timer=setTimeout(()=>{const k=resolveDestinationKey(el.value);if(k)applyDestinationTheme(k)},180)};el.addEventListener('input',run);el.addEventListener('change',run)}
document.getElementById('startManualBtn')?.addEventListener('click',()=>{showStep(2)});
document.getElementById('startTicketBtn')?.addEventListener('click',()=>{showStep(1)});
document.getElementById('tripLang')?.addEventListener('click',()=>setTimeout(applyEntryCopy,0));
setSaudiStartVisual();applyEntryCopy();watchDestination();
if(!localStorage.getItem('travo-trip-draft'))showStep(0);
const smartTripScript=document.createElement('script');smartTripScript.src='trip-smart.js';smartTripScript.onload=()=>{try{const d=JSON.parse(localStorage.getItem('travo-trip-draft')||'null');if(d?.itinerary&&d?.payload&&typeof renderItinerary==='function')renderItinerary(d.itinerary,d.payload,false)}catch{}};document.body.appendChild(smartTripScript);
