const entryStyle=document.createElement('link');entryStyle.rel='stylesheet';entryStyle.href='trip-entry.css';document.head.appendChild(entryStyle);
const ENTRY={ar:{startStep:'البداية',hero:'خطط رحلتك بذكاء.<br>وخلّ TRAVO يرتب التفاصيل.',heroSub:'ابدأ باختيار أسلوب التخطيط، وبعدها عبّئ بيانات الرحلة أو ارفع تذاكر الطيران ليقرأها TRAVO تلقائيًا.',startTitle:'خطط رحلتك بذكاء',startSub:'حدد أولًا كيف تبغى TRAVO يرتب يومك، ثم اختر طريقة إدخال الرحلة.',manualTitle:'تعبئة بيانات الرحلة',manualSub:'المغادرة والعودة ووقتهما، والفندق اختياري.',ticketMethodTitle:'رفع تذاكر الطيران',ticketMethodSub:'صوّر أو ارفع التذكرة وTRAVO يقرأ بياناتها تلقائيًا.',goalsSub:'الآن نكمل اهتماماتك، وTRAVO يستخدم أسلوب التخطيط اللي اخترته من البداية.'},en:{startStep:'Start',hero:'Plan your trip smarter.<br>Let TRAVO handle the details.',heroSub:'Choose your planning style first, then enter your trip manually or upload flight tickets for TRAVO to read.',startTitle:'Plan your trip smarter',startSub:'First choose how TRAVO should organize your days, then choose how to enter your trip.',manualTitle:'Enter trip details',manualSub:'Departure and return dates/times. Hotel is optional.',ticketMethodTitle:'Upload flight tickets',ticketMethodSub:'Take a photo or upload your ticket and TRAVO reads the trip details automatically.',goalsSub:'Now add your interests. TRAVO keeps the planning style you selected at the start.'}};
function entryLang(){return localStorage.getItem('travo-lang')||'ar'}
function applyEntryCopy(){const l=entryLang();document.querySelectorAll('[data-entry-i]').forEach(el=>{const v=ENTRY[l]?.[el.dataset.entryI];if(v)el.innerHTML=v})}
document.getElementById('startManualBtn')?.addEventListener('click',()=>{showStep(2)});
document.getElementById('startTicketBtn')?.addEventListener('click',()=>{showStep(1)});
document.getElementById('tripLang')?.addEventListener('click',()=>setTimeout(applyEntryCopy,0));
applyEntryCopy();
if(!localStorage.getItem('travo-trip-draft'))showStep(0);
const smartTripScript=document.createElement('script');smartTripScript.src='trip-smart.js';smartTripScript.onload=()=>{try{const d=JSON.parse(localStorage.getItem('travo-trip-draft')||'null');if(d?.itinerary&&d?.payload&&typeof renderItinerary==='function')renderItinerary(d.itinerary,d.payload,false)}catch{}};document.body.appendChild(smartTripScript);
